### PR TITLE
Struct tag inspection

### PR DESCRIPTION
**Pull request by cesartw**
Add ability to defined requirements through struct tags

### CODE REVIEW

**Comment by cesartw** [comment]
I was indirectly thinking about that the other day. 
DB, request(json) and DB/request API interface should be implemented with 3 different structs.

**Comment by Carpetsmoker** [comment]
I think that if you want to do this, then you should use one of the (many) existing packages that already work well, instead of re-inventing the wheel. The reason I made this package is because I personally don't really like using tags for stuff, and wanted a simple "just works" package that doesn't use it.

**Comment by cesartw** [comment]
I prefer tags as they're easier and quicker to understand. I'm aware of
other packages but it easier to implement than replace

**Comment by ready4god2513** [comment]
> DB, request(json) and DB/request API interface should be implemented with 3 different structs.

That has its own set of problems as well, though.  I suppose we could clean it up through composition, but we used to have that for some types and it got very messy (See xDB, xJSON types as an example)

**Comment by ready4god2513** [comment]
As far as using struct tags, I'm in favor.  I know it has it's own drawbacks as well, but using the tags 1: follows conventions and 2: gives a single place to go to know what is valid for the type.

**Comment by Carpetsmoker** [comment]
> they're easier and quicker to understand

I have to disagree. It's all just an untyped string and "programming by comments". It becomes rather ugly quite fast, and adding more advanced options is a huge pain. It's very easy to make stupid mistakes like typos that can go undetected got ages. Struct tags are a "necessarily evil" in Go. So ... I would personally not vote in favour of using that in Desk :-)

As for this PR, I have a stronger opinion: as mentioned, there are already many packages that implement pretty much the same as what this proposes, and I don't think that re-inventing the wheel is adding to that. It doesn't do anything better or different than other packages.

This is different from the current implementation, which *is* different than other packages (or at least, other packages I could find at the time). Whether that's a good or bad thing is something you can agree or disagree with, but by being different it adds to the eco-system.

**Comment by cesartw** [comment]
@Carpetsmoker I agree and I think it's a matter of degree. 
This is not implementing complex validation at all nor I'd expect to add anything more complex than that.
Typos can happen in every single string in the code, not just tags. Unit tests are supposed to weed them out.

**Comment by Carpetsmoker** [comment]
That is true, but e.g. `v.Reqiured()` is an error, and in a struct tag it's not :-)

At any rate, I personally don't like it for reasons outlined, but I seem to be in the minority, so guess it's okay? I'll do a review of the actual implementation later.

**Comment by JaTochNietDan** [comment]
> but I seem to be in the minority, so guess it's okay?

So you're okay with the tyranny of the majority? 😇

**Comment by cesartw** [comment]
>v.Reqiured() is an error

I can appreciate a compiling error. 
The issue also presents itself with `fmt.*printf()`. So we have lint and unit testing to cover that.
Where we draw the line?
Not going further than what go's stdlib provides, maybe? I'd agree with that but I'd have to get rid of echo and gorp too.

**Comment by cesartw** [comment]
We will be using a function per type for performing validations

**Pull request closed without merging**
